global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gitlab'
    # GitLab suele exponer métricas en '/-/metrics' si se habilitan
    metrics_path: '/admin/system_info'
    static_configs:
      - targets: ['192.168.100.16:80']

  - job_name: 'grafana'
    # Grafana expone métricas en '/metrics' si está configurado
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.100.16:3000']

  - job_name: 'prometheus'
    # Prometheus expone sus propias métricas en '/metrics'
    static_configs:
      - targets: ['192.168.100.16:9000']

  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.100.16:9101']