global:
  scrape_interval: 15s         # Intervalo global para recopilar métricas
  evaluation_interval: 15s       # Frecuencia de evaluación de reglas de alerta

scrape_configs:
  - job_name: 'prometheus'       # Trabajo para que Prometheus se scrape a sí mismo
    static_configs:
      - targets: ['localhost']  # Como Prometheus está corriendo en el puerto 9000, se apunta a sí mismo