version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - DS_PROMETHEUS=PBFA97CFB590B2093
      
volumes:
  grafana_data: